name: docker login build push shell action
description: docker login build push shell action
author: RekGRpth
runs:
  using: composite
  steps:
    - run: "${GITHUB_ACTION_PATH}/action.sh"
      shell: sh
