name: docker build push action
description: docker build push action
author: RekGRpth
inputs:
  image:
    description: docker build push image
  registry:
    description: docker build push registry
    default: ghcr.io
  tag:
    description: docker build push tag
  username:
    description: docker build push username
    default: ${{ github.repository_owner }}
runs:
  using: composite
  steps:
    - run: |
        set -eux
        GITHUB_BRANCH="${GITHUB_REF##*/}"
        GITHUB_REPOSITORY_NAME="${GITHUB_REPOSITORY##*/}"
        INPUTS_IMAGE="${{ inputs.image }}"
        INPUTS_REGISTRY="${{ inputs.registry }}"
        INPUTS_TAG="${{ inputs.tag }}"
        INPUTS_USERNAME="${{ inputs.username }}"
        REGISTRY_USERNAME_IMAGE_TAG="$(echo "${INPUTS_REGISTRY}/${INPUTS_USERNAME}/${INPUTS_IMAGE:-${GITHUB_REPOSITORY_NAME}}:${INPUTS_TAG:-${GITHUB_BRANCH}}" | tr '[:upper:]' '[:lower:]')"
        docker build --progress=plain --tag "${REGISTRY_USERNAME_IMAGE_TAG}" .
        docker push "${REGISTRY_USERNAME_IMAGE_TAG}"
      shell: sh
