name: docker login build push action
description: docker login build push action
author: RekGRpth
inputs:
  image:
    description: docker build push image
  password:
    description: docker login password
    default: ${{ github.token }}
  registry:
    description: docker build push registry
    default: ghcr.io
  tag:
    description: docker build push tag
  username:
    description: docker login build push username
    default: ${{ github.repository_owner }}
runs:
  using: composite
  steps:
    - run: |
        set -eux
        export INPUTS_IMAGE="${{ inputs.image }}"
        export INPUTS_PASSWORD="${{ inputs.password }}"
        export INPUTS_REGISTRY="${{ inputs.registry }}"
        export INPUTS_TAG="${{ inputs.tag }}"
        export INPUTS_USERNAME="${{ inputs.username }}"
        "${GITHUB_ACTION_PATH}/action.sh"
      shell: sh
