name: docker build push action
description: docker build push action
author: RekGRpth
inputs:
  image:
    description: docker build push image
  registry:
    description: docker build push registry
    default: ghcr.io
  tag:
    description: docker build push tag
  username:
    description: docker build push username
    default: ${{ github.repository_owner }}
runs:
  using: composite
  steps:
    - run: |
        set -eux
        INPUTS_IMAGE="${{ inputs.image }}"
        INPUTS_TAG="${{ inputs.tag }}"
        REGISTRY_USERNAME_IMAGE_TAG="$(echo "${{ inputs.registry }}/${{ inputs.username }}/${INPUTS_IMAGE:-${GITHUB_REPOSITORY##*/}}:${INPUTS_TAG:-${GITHUB_REF##*/}}" | tr '[:upper:]' '[:lower:]')"
        docker build --progress=plain --tag "${REGISTRY_USERNAME_IMAGE_TAG}" .
        docker push "${REGISTRY_USERNAME_IMAGE_TAG}"
      shell: sh
