name: docker login build push action
description: docker login build push action
author: RekGRpth
runs:
  using: composite
  steps:
    - run: echo "${{ toJSON(github) }}"
      shell: sh
    - run: "${GITHUB_ACTION_PATH}/action.sh"
      shell: sh
